import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { NavBar } from '@/components';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="antialiased bg-gradient-to-r from-pink-300 dark:from-slate-900 via-purple-300 dark:via-slate-600 to-indigo-400 dark:to-black h-full">
			<NavBar />
			{children}
		</div>
	);
}
